/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.MVC.mvc_prog2.br.udesc.prog2.visao;

import main.MVC.mvc_prog2.br.udesc.prog2.controlador.ControladorMarcarConsulta;
import main.MVC.mvc_prog2.br.udesc.prog2.controlador.manterpaciente.ObserverCadastro;
import main.MVC.mvc_prog2.br.udesc.prog2.modelo.Medico;
import main.MVC.mvc_prog2.br.udesc.prog2.modelo.Paciente;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author matth
 */
public class TelaMarcarConsulta extends javax.swing.JFrame implements ObserverCadastro {

    private ControladorMarcarConsulta controller;

    /**
     * Creates new form TelaMarcarConsulta
     */
    public TelaMarcarConsulta() {
        initComponents();
        this.controller = new ControladorMarcarConsulta();
        this.controller.anexar(this);
        atualizaTela();

        adicionarAcoes();
    }

    private void adicionarAcoes() {
        btnMarcarConsulta.addActionListener(e -> controller.marcarConsulta(getMedico(), getPaciente(), getData(), getHora()));

    }

    public void popularPacientes(List<Paciente> pacientes){
        for (Paciente p: pacientes)
            cbPaciente.addItem(p);
    }
    
    public void popularMedicos(List<Medico> medicos){
        for (Medico m: medicos)
            cbMedico.addItem(m);
    }
    
    public Medico getMedico(){
        Medico medico = (Medico) cbMedico.getSelectedItem();
        return medico;
    }
    
    public Paciente getPaciente(){
        Paciente paciente = (Paciente) cbPaciente.getSelectedItem();
        return paciente;
    }
    
    public String getData(){
        return edData.getText();
    }
    
    public String getHora(){
        return edHora.getText();
    }
    
    public void adicionarAcaoBtnMarcarConsulta(ActionListener acao){
        btnMarcarConsulta.addActionListener(acao);
    }

    @Override
    public void exibirMensagem(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }

    @Override
    public void atualizaTela() {
        popularPacientes(controller.getPacientes());
        popularMedicos(controller.getMedicos());
        limparTela();
    }

    public void limparTela(){
        edData.setText("");
        edHora.setText("");
        cbMedico.setSelectedIndex(0);
        cbPaciente.setSelectedIndex(0);
    }
    
    public void exibirTela(){
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPaciente = new javax.swing.JComboBox<>();
        cbMedico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edData = new javax.swing.JTextField();
        edHora = new javax.swing.JTextField();
        btnMarcarConsulta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Paciente");

        jLabel2.setText("Médico");

        btnMarcarConsulta.setText("Marcar Consulta");

        jLabel3.setText("Data");

        jLabel4.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnMarcarConsulta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(cbPaciente, 0, 153, Short.MAX_VALUE)
                                .addComponent(cbMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edData)
                                .addComponent(edHora))
                            .addComponent(jLabel4))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(edData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMarcarConsulta)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMarcarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarConsulta;
    private javax.swing.JComboBox<Medico> cbMedico;
    private javax.swing.JComboBox<Paciente> cbPaciente;
    private javax.swing.JTextField edData;
    private javax.swing.JTextField edHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
